version: '3.7'

services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis-local'
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


