version: '3.7'

services:
  #  redis:
  #    image: 'redis:alpine'
  #    container_name: 'redis-local'
  #    volumes:
  #      - ./data/redis:/data
  #    command: redis-server --appendonly yes
  #    ports:
  #      - '6379:6379'
  #    restart: always
  #    networks:
  #      - app-network

  pg:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  session_pg:
    image: 'postgres:16'
    ports:
      - '6000:6000'
    environment:
      - POSTGRES_PASSWORD=session_db
      - POSTGRES_DB=session_db
      - POSTGRES_USER=session_db
    volumes:
      - ./data/session_postgres:/var/lib/postgresql/session_db/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
